version: 2

sources:
  - name: transactions_db
    description: Raw transactional data source from ClickHouse.
    database: transactions_db
    schema: transactions_db
    tables:
      - name: transactions
        description: Table containing transactional data with fraud indicator.
        columns:
          - name: transaction_time
            description: "Timestamp of the transaction."
          - name: merch
            description: "Merchant identifier."
          - name: cat_id
            description: "Transaction category."
          - name: amount
            description: "Transaction amount."
          - name: name_1
            description: "First name of the customer."
          - name: name_2
            description: "Last name of the customer."
          - name: gender
            description: "Gender of the customer (M/F)."
          - name: street
            description: "Street address of the customer."
          - name: one_city
            description: "City of the customer."
          - name: us_state
            description: "US state code of the customer."
          - name: post_code
            description: "Postal code of the customer."
          - name: lat
            description: "Latitude of the customer."
          - name: lon
            description: "Longitude of the customer."
          - name: population_city
            description: "Population of the customer's city."
          - name: jobs
            description: "Job description or sector for the customer."
          - name: merchant_lat
            description: "Latitude of the merchant location."
          - name: merchant_lon
            description: "Longitude of the merchant location."
          - name: target
            description: "Fraud indicator (1=fraud, 0=legit)."
            tests:
              - accepted_values:
                  values: [0, 1]
